# syntax=docker/dockerfile:1

# Start from golang:1.22-alpine base image
FROM golang:1.22.1

# Set destination for COPY
WORKDIR /app

# Download Go modules
COPY go.mod go.sum ./
RUN go mod download

# Copy the source from the current directory
# to the Working Directory inside the container
COPY ./cmd/auth ./cmd/auth
COPY ./internal/auth ./internal/auth
COPY ./pkg ./pkg

COPY ./proto/google ./proto/google
COPY ./proto/protoc-gen-openapiv2 ./proto/protoc-gen-openapiv2
COPY ./proto/auth ./proto/auth

COPY ./auth.ed ./auth.ed.pub ./

# Build the Go app
RUN apt-get update
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 \
    go build -o ./bin ./cmd/auth/main.go

# Command to run the executable
CMD ["/app/bin"]